In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Creating variables (which are tensors). This one has rank 0

In [2]:
my_tensor_string = tf.Variable("I am Chris", tf.string)
print(my_tensor_string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'I am Chris'>


Tensors are multidimensional vectors. Their rank is how many dimensions they have.

The first example is one, storing three elements.
The second is two, storing two elements

In [6]:
rank_1 = tf.Variable([5, 6, 7], tf.int16)
rank_2 = tf.Variable([[1, 2]], tf.int16)
print(tf.rank(rank_1))
print(tf.rank(rank_2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# Shape

The shape of a tensor is how many elements are in each of its layers

In [7]:
print(rank_1.shape)
print(rank_2.shape)

(3,)
(1, 2)


# Reshape

You can change the shape of a tensor using the `.reshape` method.  
As long as the numbers multiply to be identical, then it will work

In [10]:
tensor1 = tf.ones([1, 2, 3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [3, 2, 1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
